import { useApp } from '../lib/store';
import { declareWinner } from '../lib/tournamentLogic';
import { useState } from 'react';

export default function Matches() {
  const { state, dispatch } = useApp();
  const [selectedDiv, setSelectedDiv] = useState('');
  const [printing, setPrinting] = useState(false);
  const divNames = Object.keys(state.brackets);

  const handleWinner = (matchId, winnerId) => {
    const rounds = JSON.parse(JSON.stringify(state.brackets[selectedDiv]));
    const updated = declareWinner(rounds, matchId, winnerId);
    dispatch({ type: 'UPDATE_BRACKETS', division: selectedDiv, rounds: updated });
    const finalMatch = updated[updated.length - 1][0];
    if (finalMatch.winner) {
      const gold = finalMatch.winner;
      const silver = finalMatch.loser;
      const bronzes = [];
      if (updated.length >= 2) {
        updated[updated.length - 2].forEach(m => {
          if (m.loser && m.loser.id !== silver?.id) bronzes.push(m.loser);
        });
      }
      dispatch({ type: 'SET_RESULT', division: selectedDiv, result: { gold, silver, bronzes } });
    }
  };

  const handlePrintResults = () => {
    setPrinting(true);
    setTimeout(() => {
      window.print();
      setPrinting(false);
    }, 100);
  };

  const rounds = selectedDiv ? state.brackets[selectedDiv] : null;
  const result = selectedDiv ? state.results[selectedDiv] : null;

  return (
    <div>
      {/* ── PRINTABLE RESULTS SHEET (hidden on screen, shown only on print) ── */}
      {printing && result && (
        <div className="print-results-sheet">
          <style>{`
            @media print {
              body * { visibility: hidden !important; }
              .print-results-sheet, .print-results-sheet * { visibility: visible !important; }
              .print-results-sheet {
                position: fixed !important;
                top: 0; left: 0; right: 0; bottom: 0;
                background: white !important;
                z-index: 99999;
                padding: 40px;
              }
            }
          `}</style>

          {/* Header */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', paddingBottom: '20px', borderBottom: '3px solid #000', marginBottom: '32px' }}>
            {state.settings.logo && <img src={state.settings.logo} alt="" style={{ height: '64px', border: '2px solid #000' }} />}
            <div>
              <h1 style={{ fontSize: '28px', fontWeight: 900, margin: 0, fontFamily: '"Space Mono", monospace' }}>
                {state.settings.name || 'TOURNAMENT'}
              </h1>
              <h2 style={{ fontSize: '16px', fontWeight: 600, color: '#666', margin: '4px 0 0' }}>
                OFFICIAL RESULTS — {selectedDiv}
              </h2>
            </div>
          </div>

          {/* Results Table */}
          <table style={{ width: '100%', borderCollapse: 'collapse', fontFamily: '"Space Grotesk", sans-serif' }}>
            <thead>
              <tr>
                <th style={thStyle}>POSITION</th>
                <th style={thStyle}>MEDAL</th>
                <th style={thStyle}>ATHLETE NAME</th>
                <th style={thStyle}>CLUB / TEAM</th>
              </tr>
            </thead>
            <tbody>
              {result.gold && (
                <tr>
                  <td style={tdStyle}>1st</td>
                  <td style={{ ...tdStyle, fontWeight: 900, color: '#f59e0b' }}>GOLD</td>
                  <td style={{ ...tdStyle, fontWeight: 700 }}>{result.gold.name}</td>
                  <td style={tdStyle}>{result.gold.club || '-'}</td>
                </tr>
              )}
              {result.silver && (
                <tr>
                  <td style={tdStyle}>2nd</td>
                  <td style={{ ...tdStyle, fontWeight: 900, color: '#6b7280' }}>SILVER</td>
                  <td style={{ ...tdStyle, fontWeight: 700 }}>{result.silver.name}</td>
                  <td style={tdStyle}>{result.silver.club || '-'}</td>
                </tr>
              )}
              {result.bronzes?.map((b, i) => (
                <tr key={i}>
                  <td style={tdStyle}>3rd</td>
                  <td style={{ ...tdStyle, fontWeight: 900, color: '#b45309' }}>BRONZE</td>
                  <td style={{ ...tdStyle, fontWeight: 700 }}>{b.name}</td>
                  <td style={tdStyle}>{b.club || '-'}</td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Footer */}
          <div style={{ marginTop: '48px', paddingTop: '16px', borderTop: '2px solid #000', display: 'flex', justifyContent: 'space-between', fontSize: '12px', color: '#999' }}>
            <span>Generated by TKD Neo — Tournament Manager</span>
            <span>{new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</span>
          </div>
        </div>
      )}

      {/* ── SCREEN UI ── */}
      <h2 className="text-3xl font-black tracking-tight mb-1 no-print" style={{ fontFamily: 'var(--font-mono)' }}>RUN MATCHES</h2>
      <p className="text-sm text-gray-500 mb-4 no-print">Select winners to advance through rounds</p>
      <div className="mb-6 no-print">
        <select className="brutal-select w-64" value={selectedDiv} onChange={e => setSelectedDiv(e.target.value)}>
          <option value="">Select Division</option>
          {divNames.map(d => <option key={d} value={d}>{d}</option>)}
        </select>
      </div>

      {!rounds ? (
        <div className="brutal-card p-12 text-center no-print">
          <div className="icon-circle w-16 h-16 text-xl grad-red mx-auto mb-4">M</div>
          <p className="text-gray-400 font-medium">Generate brackets first, then run matches</p>
        </div>
      ) : (
        <>
          {/* Completion banner */}
          {rounds[rounds.length - 1][0].winner && (
            <div className="brutal-card mb-6 overflow-hidden no-print">
              <div className="grad-green text-white p-6 text-center">
                <h3 className="text-xl font-black uppercase tracking-wider mb-1">DIVISION COMPLETE</h3>
                <p className="text-sm opacity-90 mb-4">
                  Winner: <strong>{rounds[rounds.length - 1][0].winner.name}</strong>
                </p>
                <button onClick={handlePrintResults} className="brutal-btn brutal-btn-white text-sm">
                  DOWNLOAD RESULTS PDF
                </button>
              </div>
            </div>
          )}

          <div className="space-y-4 max-w-lg no-print">
            {rounds.map((round, rIdx) => {
              const roundLabel = rIdx === rounds.length - 1 ? 'FINAL' : rIdx === rounds.length - 2 ? 'SEMI-FINAL' : `ROUND ${rIdx + 1}`;
              return round.map((match, mIdx) => {
                if (match.player2?.id === 'BYE') return null;
                const p1 = match.player1, p2 = match.player2;
                return (
                  <div key={match.id} className="brutal-card overflow-hidden">
                    <div className="px-5 py-3 grad-dark text-white text-xs font-bold uppercase tracking-wider">
                      {roundLabel} — Match {mIdx + 1}
                    </div>
                    <div className="p-5">
                      <div className="flex items-center gap-3 mb-4">
                        <div className="flex-1 brutal-card p-3 text-center border-2" style={{ boxShadow: '3px 3px 0 var(--color-blue)', borderColor: 'var(--color-blue)' }}>
                          <div className="font-bold text-sm">{p1?.name || 'TBD'}</div>
                          <div className="text-xs text-gray-500">{p1?.club || ''}</div>
                        </div>
                        <span className="font-black text-lg text-gray-300">VS</span>
                        <div className="flex-1 brutal-card p-3 text-center border-2" style={{ boxShadow: '3px 3px 0 var(--color-red)', borderColor: 'var(--color-red)' }}>
                          <div className="font-bold text-sm">{p2?.name || 'TBD'}</div>
                          <div className="text-xs text-gray-500">{p2?.club || ''}</div>
                        </div>
                      </div>
                      {match.winner ? (
                        <div className="grad-green text-white border-3 border-black p-3 text-center text-sm font-bold">
                          WINNER: {match.winner.name}
                        </div>
                      ) : p1 && p2 ? (
                        <div className="flex gap-2">
                          <button onClick={() => handleWinner(match.id, p1.id)} className="brutal-btn brutal-btn-blue flex-1 text-xs">
                            BLUE — {p1.name}
                          </button>
                          <button onClick={() => handleWinner(match.id, p2.id)} className="brutal-btn brutal-btn-red flex-1 text-xs">
                            RED — {p2.name}
                          </button>
                        </div>
                      ) : (
                        <div className="grad-amber text-white border-3 border-black p-3 text-center text-sm font-bold">
                          WAITING FOR PREVIOUS MATCHES
                        </div>
                      )}
                    </div>
                  </div>
                );
              });
            })}
          </div>
        </>
      )}
    </div>
  );
}

const thStyle = {
  textAlign: 'left',
  padding: '14px 16px',
  fontSize: '11px',
  fontWeight: 800,
  textTransform: 'uppercase',
  letterSpacing: '1.5px',
  background: '#000',
  color: '#fff',
  border: '2px solid #000',
};

const tdStyle = {
  padding: '14px 16px',
  fontSize: '14px',
  border: '2px solid #000',
};
